### ISSUE TITLE
how to work?

### ISSUE THREAD

**Issue by friend-ma** [idealclover/student-information-management-system#2]
it did't work ....
ERROR:
`Traceback (most recent call last):
  File "C:/Users/Master/Desktop/student-information-management-system-master/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "D:\python-3.6.2\lib\site-packages\django\core\management\__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "D:\python-3.6.2\lib\site-packages\django\core\management\__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "D:\python-3.6.2\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "D:\python-3.6.2\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "D:\python-3.6.2\lib\site-packages\django\conf\__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "D:\python-3.6.2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'SIMS.settings'
`

I need what are pakeages?

**Comment by idealclover** [comment]
Well, in fact the project has not finished yet and I'm ready to rewrite it in django 2.0. The problem may be caused by my mistake in folder "SIMS". I will rewrite the project as soon as possible after the exams. Sorry!

**Comment by idealclover** [comment]
oops, that's because I forgot to update my files in the floder "SIMS" so that it's empty. QAQ I'll rewrite it after the exams.

**Comment by friend-ma** [comment]
soga~ preparation for the exam, thank you very much.
